# Generated by Django 5.0.6 on 2024-06-12 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('maintenance_date', models.DateField()),
                ('exchange_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AirQualityData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=100)),
                ('measure_time', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('iat', models.FloatField()),
                ('ion', models.FloatField()),
                ('ax', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ay', models.DecimalField(decimal_places=2, max_digits=4)),
                ('az', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gx', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gz', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pm1m', models.FloatField()),
                ('pm25m', models.FloatField()),
                ('pm4m', models.FloatField()),
                ('pm10m', models.FloatField()),
                ('pm1n', models.FloatField()),
                ('pm25n', models.FloatField()),
                ('pm10n', models.FloatField()),
                ('pm4n', models.FloatField()),
                ('pts', models.FloatField()),
                ('vel', models.SmallIntegerField()),
                ('address', models.CharField(max_length=150)),
                ('air_quality_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.airqualitymeter')),
            ],
            options={
                'verbose_name': 'Air Quality Data',
                'verbose_name_plural': 'Air Quality Data',
                'ordering': ['-measure_time'],
            },
        ),
        migrations.CreateModel(
            name='MicroController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aratu_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('maintenance_date', models.DateField()),
                ('exchange_date', models.DateField()),
                ('acquisition_date', models.DateField()),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('air_quality_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.airqualitymeter')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('acquisition_date', models.DateField()),
                ('maintenance_date', models.DateField()),
                ('exchange_date', models.DateField()),
                ('microcontroller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.microcontroller')),
            ],
        ),
    ]
