# Generated by Django 5.0.6 on 2024-06-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airqualitydata',
            old_name='iat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='airqualitydata',
            old_name='ion',
            new_name='lon',
        ),
    ]
