# Generated by Django 5.0.6 on 2024-06-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_rename_iat_airqualitydata_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualitydata',
            name='air_quality_meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='air_quality_data', to='sensor.airqualitymeter'),
        ),
        migrations.AlterField(
            model_name='airqualitydata',
            name='vel',
            field=models.SmallIntegerField(default=0),
        ),
    ]
