# Generated by Django 5.0.6 on 2024-10-30 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_airqualitydata_air_quality_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airqualitymeter',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='airqualitymeter',
            name='exchange_date',
        ),
        migrations.RemoveField(
            model_name='airqualitymeter',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='exchange_date',
        ),
        migrations.RemoveField(
            model_name='microcontroller',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='acquisition_date',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='exchange_date',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='maintenance_date',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='model',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='serial_number',
        ),
    ]
