# Generated by Django 5.0.6 on 2025-03-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_remove_airqualitymeter_acquisition_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('how_many_days', models.IntegerField()),
            ],
        ),
    ]
