# Generated by Django 5.0.6 on 2025-05-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_predicteddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_interval_days', models.PositiveIntegerField(default=30)),
                ('data_retention_days', models.PositiveIntegerField(default=90)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('max_db_size_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
